-
  name: Configure mariadb on database servers
  hosts: dbvms
  vars:
    packages:
    - MySQL-python
    - mariadb-server
  tasks:
  - name: Install mariadb
    yum:
      name: "{{ item }}"
      state: latest
    loop: '{{ packages }}'
  - name: Start mariadb service
    service:
      name: mariadb
      state: started
  - name: Allow port 3306 on server firewall
    firewalld:
      port: 3306/tcp
      permanent: true
      state: enabled
  - name: Create a new database with name ecomdb
    mysql_db:
      name: ecomdb
      state: present
  - name: Create a new user and grant priviledge
    mysql_user:
      name: ecomuser
      password: ecompassword
      priv: '*.*:ALL,GRANT'
      state: present 
  - name: Create the db-load-script.sql
    #command: touch '{{ item }}' ; chmod +x '{{ item }}'
    shell: |
      touch '{{ item }}'
      chmod +x '{{ item }}'
    loop:
    - /db-load-script.sql
    - /script.sh
  - name: Populate the script with data
    blockinfile:
      path: /db-load-script.sql
      block: |
        USE ecomdb;
        CREATE TABLE products (id mediumint(8) unsigned NOT NULL auto_increment,Name varchar(255) default NULL,Price varchar(255) default NULL, ImageUrl varchar(255) default NULL,PRIMARY KEY (id)) AUTO_INCREMENT=1;
        INSERT INTO products (Name,Price,ImageUrl) VALUES ("Laptop","100","c-1.png"),("Drone","200","c-2.png"),("VR","300","c-3.png"),("Tablet","50","c-5.png"),("Watch","90","c-6.png"),("Phone Covers","20","c-7.png"),("Phone","80","c-8.png"),("Laptop","150","c-4.png");
  
  - name: Run script.sh
    script: /project/new_project/mysqlscript.sh


-
  name: Deploy and Configure Web
  hosts: webvms
  vars:
    web_packages:
    - httpd
    - php
    - php-mysql
    - git
  tasks:
  - name: Install the required Web packages
    yum:
      name: "{{ item }}"
      state: latest
    loop: '{{ web_packages }}'

  - name: Replace a line in httpd.conf
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^DirectoryIndex index.html'
      line: 'DirectoryIndex index.php'
      backrefs: yes

  - name: STart and enable httpd service
    service:
      name: httpd
      state: started
      enabled: yes

  - name: to check if the file /var/www/html/flag_new exists
    stat:
      path: /var/www/html/flag_new
    register: file_data

  - name: Clone a Git repo
    git:
      repo: 'https://github.com/kodekloudhub/learning-app-ecommerce.git'
      dest: /var/www/html/
    when: not file_data.stat.exists

  - name: Point the web server to the database server
    replace:
      path: /var/www/html/index.php
      regexp: '172.20.1.101'
      replace: '10.0.1.8'

  - name: Read the contents of index.html 
    shell: cat /var/www/html/index.php
    register: index_content

  - name: touch a file when the index is already replaced with 10.0.1.8
    command: touch /var/www/html/flag_new
    when: index_content.stdout.find('10.0.1.8') != -1

  - name: Allow port 80 on server firewall
    firewalld:
      port: 80/tcp
      permanent: true
      state: enabled
